name: Automate Paraulogic Tasks

on:
  schedule:
    # Run the workflow every day at 2:10 UTC 
    - cron: '5 22 * * *' 
    - cron: '5 23 * * *' 
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  scrape-data:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install
  
    # Step 3: Run the Python scripts
    - name: Run Python file to get solution
      run: python paraulogic.py

    - name: Run Python file to create HTML
      run: python write_solution.py

    # Step 4: Push changes to the repository
    - name: Configure Git user
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit changes
      run: |
        git add .
        git commit -m "Update the contents of solution text file" || echo "No changes to commit"
      
    - name: Push changes
      run: |
        git push https://$GH_TOKEN@github.com/${{ github.repository }}.git HEAD:${{ github.ref }} --force
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
