name: Automate Paraulogic Tasks

on:
  schedule:
    # Run the workflow every day at :300 UTC
    - cron: '0 3 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  scrape-data:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Installing package list
      run: apt list --installed    
    - name: Removing previous chrome instances on runner 
      run: sudo apt purge google-chrome-stable  

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # Need to fetch reqs if needed
    #- name: Installing all necessary packages
    #  run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay
    - name: Install xvfb
      run: sudo apt-get install xvfb

    #- name: Update APT
    #  run: |
    #    for i in {1..3}; do
    #      sudo apt-get update && break || sleep 10
    #    done
    #    sudo apt-get install -y wget curl unzip
        
    # Step 4: Install Chrome and ChromeDriver
    #- name: Install Specific Chrome Version
    #  run: |
    #    wget -q https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_131.0.6778.139-1_amd64.deb
    #    #sudo apt install -y ./google-chrome-stable_131.0.6778.139-1_amd64.deb
    #    #google-chrome --version
    #    sudo dpkg -i google-chrome-stable_131.0.6778.139-1_amd64.deb
    #    sudo apt-get -f install  # To fix any missing dependencies

    
    #- name: Install Matching ChromeDriver
    #  run: |
    #    CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
    #    echo "Chrome version is: $CHROME_VERSION"
    #    DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
    #    wget -q "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
    #    unzip -o chromedriver_linux64.zip
    #    sudo mv chromedriver /usr/bin/chromedriver
    #    sudo chmod +x /usr/bin/chromedriver
    #    chromedriver --version

    # Step 5: Debug Chrome Installation
    #- name: Debug Chrome Installation
    #  run: |
    #    ls -l /usr/bin/google-chrome
    #    google-chrome --version

    # Step 6: Run the Python script
    - name: Run Python file
      run: python paraulogic.py

    # Step 7: Push changes to the repository
    - name: Configure Git user
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit changes
      run: |
        git add .
        git commit -m "Update the contents of solution text file" || echo "No changes to commit"
      
    - name: Push changes
      run: |
        git push https://$GH_TOKEN@github.com/${{ github.repository }}.git HEAD:${{ github.ref }} --force
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
