name: Automate Paraulogic Tasks

on:
  schedule:
    # Run the workflow every day at :300 UTC
    - cron: '0 3 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  scrape-data:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Install Chrome and ChromeDriver
    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        google-chrome --version  # Verify installation

    - name: Install ChromeDriver
      run: |
        sudo apt-get install -y chromium-chromedriver
        chromedriver --version  # Verify installation

    # Step 5: Run the Python script
    - name: Run Python file
      run: python paraulogic.py

    # Step 6: Push changes to the repository
    - name: Configure Git user
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit changes
      run: |
        git add .
        git commit -m "Update the contents of solution text file" || echo "No changes to commit"
      
    - name: Push changes
      run: |
        git push https://$GH_TOKEN@github.com/${{ github.repository }}.git HEAD:${{ github.ref }} --force
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

